export const sample_foods=[
    {
        id:'1',
        name: 'Pizza',
        cookTime: '10-20',
        price:10,
        favorites: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'food-1.jpg',
        tags: ['FastFood','Pizza','Lunch'],
    },
    {
        id:'2',
        name: 'Meatballs',
        cookTime: '20-30',
        price:20,
        favorites: true,
        origins: ['persia,middle east'],
        stars: 4.9,
        imageUrl: 'food-2.jpg',
        tags: ['Slowfood','Lunch'],  
    }, 
    {
        id:'3',
        name: 'HamBURGER',
        cookTime: '10-15',
        price:15,
        favorites: true,
        origins: ['us','middle east'],
        stars: 5.0,
        imageUrl: 'food-3.jpg',
        tags: ['FastFood','HAmBUrger'],
    },
    {
        id:'4',
        name: 'Fried Potatoes',
        cookTime: '15-20',
        price:5,
        favorites: true,
        origins: ['belgium','france'],
        stars: 3.5,
        imageUrl: 'food-4.jpg',
        tags: ['FastFood','fry'],
    },
    {
        id:'5',
        name: 'Soup',
        cookTime: '10-15',
        price:5,
        favorites: true,
        origins: ['china'],
        stars: 4.0,
        imageUrl: 'food-5.jpg',
        tags: ['soup'], 
    },
    {
        id:'6',
        name: 'Vegetable Pizza',
        cookTime: '40-50',
        price:9,
        favorites: true,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'food-6.jpg',
        tags: ['Pizzzaa'], 
    }
];